name: GitHub Actions Demo

on:
  push:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le repository
        uses: actions/checkout@v4

      - name: Exécuter le script Python
        run: python job.py

      - name: Créer un fichier
        run: echo "Bonjour depuis GitHub Actions" > resultat.txt

      - name: Upload de l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: mon-resultat
          path: resultat.txt

      - name: Exécuter les tests
        run: python -m unittest test_addition.py

      - name: Vérifier le secret
        run: |
          if [ -n "$SECRET_API_TOKEN" ]; then
            echo "Le secret est bien accessible"
          else
            echo "Le secret n'est pas accessible"
            exit 1
          fi
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}

      - name: Exécuter le script secret
          run: python job_secret.py
          env:
            SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}


# name: GitHub Actions Demo

# on:
#   schedule:
#     - cron: '* * * * *'
   

# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: python job.py
#       - run: echo "Bonjour depuis GitHub Actions" > resultat.txt
#       - name: Upload resultat
#         uses: actions/upload-artifact@v4
#         with:
#           name: mon-resultat
#           path: resultat.txt





# name: GitHub Actions Demo

# on:
#   workflow_dispatch:

# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: python job.py


# name: GitHub Actions Demo
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4  
#       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - run: python job.py

